### ISSUE TITLE
there are hard coded paths in the package.el

### ISSUE THREAD

**Issue by autosquid** [Gwydir8/Spacemacs-Private-Layers#1]
these paths made configuration complex, could you remove it with auto-config things?

**Comment by gwydirsam** [comment]
I haven't quite maintained this repo. Which layers in particular?

**Comment by autosquid** [comment]
in `cedet` ;)

**Comment by gwydirsam** [comment]
Ah -- I have since abandoned using the bleeding edge version of cedet in favor of just using the semantic layer included with spacemacs (it didn't exist at the time). I did this because it was a huge pain making sure I initialized the bleeding edge version first. I'd suggest going that route. 

Otherwise, submit a pull request.
